-- SUPABASE / POSTGRESQL SCHEMA
-- Converted from PET-SHOP-MANAGEMENT-SYSTEM-CLINIC-V2-DEEP-AUDITED
-- Empty schema: no sample/static records.
-- Run this in Supabase -> SQL Editor -> New query -> Run.

-- Clean reinstall (safe only if you intentionally want to recreate an EMPTY schema)
DROP VIEW IF EXISTS public.v_sales_summary;
DROP VIEW IF EXISTS public.v_product_inventory;
DROP VIEW IF EXISTS public.v_current_confinement;
DROP VIEW IF EXISTS public.v_pet_list;

DROP TABLE IF EXISTS public.inventory_movements CASCADE;
DROP TABLE IF EXISTS public.sale_items CASCADE;
DROP TABLE IF EXISTS public.sales CASCADE;
DROP TABLE IF EXISTS public.inventory CASCADE;
DROP TABLE IF EXISTS public.products CASCADE;
DROP TABLE IF EXISTS public.categories CASCADE;
DROP TABLE IF EXISTS public.suppliers CASCADE;
DROP TABLE IF EXISTS public.confinements CASCADE;
DROP TABLE IF EXISTS public.pets CASCADE;
DROP TABLE IF EXISTS public.customers CASCADE;
DROP TABLE IF EXISTS public.user_permissions CASCADE;
DROP TABLE IF EXISTS public.users CASCADE;
DROP TABLE IF EXISTS public.settings CASCADE;

CREATE OR REPLACE FUNCTION public.set_updated_at()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$;

CREATE TABLE public.users (
  user_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username varchar(50) NOT NULL UNIQUE,
  password varchar(255) NOT NULL,
  full_name varchar(100) NOT NULL,
  role varchar(20) NOT NULL DEFAULT 'Staff'
    CHECK (role IN ('Administrator','Staff')),
  status varchar(20) NOT NULL DEFAULT 'Active'
    CHECK (status IN ('Active','Inactive')),
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE public.user_permissions (
  permission_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NOT NULL REFERENCES public.users(user_id)
    ON UPDATE CASCADE ON DELETE CASCADE,
  permission_key varchar(80) NOT NULL,
  allowed boolean NOT NULL DEFAULT false,
  UNIQUE (user_id, permission_key)
);

CREATE TABLE public.customers (
  customer_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_code varchar(20) NOT NULL UNIQUE,
  full_name varchar(120) NOT NULL,
  phone varchar(30),
  email varchar(120),
  address varchar(255),
  status varchar(20) NOT NULL DEFAULT 'Active'
    CHECK (status IN ('Active','Inactive')),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE public.pets (
  pet_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pet_code varchar(20) NOT NULL UNIQUE,
  customer_id bigint NOT NULL REFERENCES public.customers(customer_id)
    ON UPDATE CASCADE ON DELETE RESTRICT,
  pet_name varchar(100) NOT NULL,
  species varchar(50),
  breed varchar(100),
  age_years smallint NOT NULL DEFAULT 0 CHECK (age_years >= 0),
  age_months smallint NOT NULL DEFAULT 0 CHECK (age_months >= 0),
  gender varchar(20) NOT NULL DEFAULT 'Unknown'
    CHECK (gender IN ('Male','Female','Unknown')),
  health_status varchar(30) NOT NULL DEFAULT 'Healthy'
    CHECK (health_status IN ('Healthy','Under Observation','Needs Treatment','Recovering','Critical')),
  vaccination_record text,
  medical_notes text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE public.confinements (
  confinement_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pet_id bigint NOT NULL REFERENCES public.pets(pet_id)
    ON UPDATE CASCADE ON DELETE RESTRICT,
  customer_id bigint NOT NULL REFERENCES public.customers(customer_id)
    ON UPDATE CASCADE ON DELETE RESTRICT,
  admission_date timestamptz NOT NULL,
  expected_discharge_date timestamptz,
  actual_discharge_date timestamptz,
  kennel_cage varchar(50),
  status varchar(30) NOT NULL DEFAULT 'Admitted'
    CHECK (status IN ('Admitted','Under Observation','Stable','Recovering','Critical','Ready for Discharge','Discharged')),
  reason text NOT NULL,
  veterinary_notes text,
  created_by bigint REFERENCES public.users(user_id)
    ON UPDATE CASCADE ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE public.categories (
  category_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  category_name varchar(100) NOT NULL UNIQUE,
  description varchar(255),
  status varchar(20) NOT NULL DEFAULT 'Active'
    CHECK (status IN ('Active','Inactive')),
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE public.suppliers (
  supplier_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  supplier_code varchar(20) NOT NULL UNIQUE,
  supplier_name varchar(120) NOT NULL,
  contact_person varchar(100),
  phone varchar(30),
  email varchar(120),
  address varchar(255),
  status varchar(20) NOT NULL DEFAULT 'Active'
    CHECK (status IN ('Active','Inactive')),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE public.products (
  product_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sku varchar(50) NOT NULL UNIQUE,
  category_id bigint NOT NULL REFERENCES public.categories(category_id)
    ON UPDATE CASCADE ON DELETE RESTRICT,
  supplier_id bigint REFERENCES public.suppliers(supplier_id)
    ON UPDATE CASCADE ON DELETE SET NULL,
  product_name varchar(150) NOT NULL,
  description text,
  unit varchar(30) NOT NULL DEFAULT 'piece',
  cost_price numeric(12,2) NOT NULL DEFAULT 0.00 CHECK (cost_price >= 0),
  selling_price numeric(12,2) NOT NULL DEFAULT 0.00 CHECK (selling_price >= 0),
  reorder_level integer NOT NULL DEFAULT 0 CHECK (reorder_level >= 0),
  status varchar(20) NOT NULL DEFAULT 'Active'
    CHECK (status IN ('Active','Inactive')),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE public.inventory (
  inventory_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id bigint NOT NULL UNIQUE REFERENCES public.products(product_id)
    ON UPDATE CASCADE ON DELETE CASCADE,
  quantity integer NOT NULL DEFAULT 0 CHECK (quantity >= 0),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE public.inventory_movements (
  movement_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id bigint NOT NULL REFERENCES public.products(product_id)
    ON UPDATE CASCADE ON DELETE RESTRICT,
  movement_type varchar(10) NOT NULL
    CHECK (movement_type IN ('IN','OUT','SET')),
  quantity integer NOT NULL DEFAULT 0 CHECK (quantity >= 0),
  previous_quantity integer NOT NULL DEFAULT 0 CHECK (previous_quantity >= 0),
  new_quantity integer NOT NULL DEFAULT 0 CHECK (new_quantity >= 0),
  notes varchar(255),
  created_by bigint REFERENCES public.users(user_id)
    ON UPDATE CASCADE ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE public.sales (
  sale_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  invoice_number varchar(40) NOT NULL UNIQUE,
  customer_id bigint REFERENCES public.customers(customer_id)
    ON UPDATE CASCADE ON DELETE SET NULL,
  sold_by bigint REFERENCES public.users(user_id)
    ON UPDATE CASCADE ON DELETE SET NULL,
  service_type varchar(80) NOT NULL DEFAULT 'Product Sale',
  service_description varchar(255),
  sale_date timestamptz NOT NULL DEFAULT now(),
  subtotal numeric(12,2) NOT NULL DEFAULT 0.00 CHECK (subtotal >= 0),
  discount numeric(12,2) NOT NULL DEFAULT 0.00 CHECK (discount >= 0),
  total_amount numeric(12,2) NOT NULL DEFAULT 0.00 CHECK (total_amount >= 0),
  payment_method varchar(30) NOT NULL DEFAULT 'Cash'
    CHECK (payment_method IN ('Cash','Card','GCash','Bank Transfer','Other')),
  reference_number varchar(100),
  amount_paid numeric(12,2) NOT NULL DEFAULT 0.00 CHECK (amount_paid >= 0),
  change_amount numeric(12,2) NOT NULL DEFAULT 0.00 CHECK (change_amount >= 0),
  status varchar(20) NOT NULL DEFAULT 'Completed'
    CHECK (status IN ('Completed','Voided','Pending')),
  notes varchar(255)
);

CREATE TABLE public.sale_items (
  sale_item_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sale_id bigint NOT NULL REFERENCES public.sales(sale_id)
    ON UPDATE CASCADE ON DELETE CASCADE,
  product_id bigint NOT NULL REFERENCES public.products(product_id)
    ON UPDATE CASCADE ON DELETE RESTRICT,
  quantity integer NOT NULL CHECK (quantity > 0),
  unit_price numeric(12,2) NOT NULL CHECK (unit_price >= 0),
  discount numeric(12,2) NOT NULL DEFAULT 0.00 CHECK (discount >= 0),
  line_total numeric(12,2) NOT NULL CHECK (line_total >= 0)
);

CREATE TABLE public.settings (
  setting_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  setting_key varchar(100) NOT NULL UNIQUE,
  setting_value text,
  updated_at timestamptz NOT NULL DEFAULT now()
);

-- PostgreSQL replacement for MySQL "ON UPDATE CURRENT_TIMESTAMP".
CREATE TRIGGER trg_customers_updated_at BEFORE UPDATE ON public.customers
FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
CREATE TRIGGER trg_pets_updated_at BEFORE UPDATE ON public.pets
FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
CREATE TRIGGER trg_confinements_updated_at BEFORE UPDATE ON public.confinements
FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
CREATE TRIGGER trg_suppliers_updated_at BEFORE UPDATE ON public.suppliers
FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
CREATE TRIGGER trg_products_updated_at BEFORE UPDATE ON public.products
FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
CREATE TRIGGER trg_inventory_updated_at BEFORE UPDATE ON public.inventory
FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
CREATE TRIGGER trg_settings_updated_at BEFORE UPDATE ON public.settings
FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

CREATE VIEW public.v_pet_list
WITH (security_invoker = true) AS
SELECT p.pet_id,p.pet_code,p.pet_name,c.customer_code,c.full_name AS owner_name,
       p.species,p.breed,p.age_years,p.age_months,p.gender,p.health_status,
       p.vaccination_record,p.medical_notes
FROM public.pets p
JOIN public.customers c ON c.customer_id=p.customer_id;

CREATE VIEW public.v_current_confinement
WITH (security_invoker = true) AS
SELECT co.confinement_id,p.pet_code,p.pet_name,c.full_name AS owner_name,
       co.admission_date,co.expected_discharge_date,co.kennel_cage,
       co.status,co.reason,co.veterinary_notes
FROM public.confinements co
JOIN public.pets p ON p.pet_id=co.pet_id
JOIN public.customers c ON c.customer_id=co.customer_id
WHERE co.status <> 'Discharged';

CREATE VIEW public.v_product_inventory
WITH (security_invoker = true) AS
SELECT p.product_id,p.sku,p.product_name,cat.category_name,s.supplier_name,
       COALESCE(i.quantity,0) AS quantity,p.reorder_level,p.selling_price,
       CASE
         WHEN COALESCE(i.quantity,0)=0 THEN 'Out of Stock'
         WHEN COALESCE(i.quantity,0)<=p.reorder_level THEN 'Low Stock'
         ELSE 'In Stock'
       END AS stock_status
FROM public.products p
JOIN public.categories cat ON cat.category_id=p.category_id
LEFT JOIN public.suppliers s ON s.supplier_id=p.supplier_id
LEFT JOIN public.inventory i ON i.product_id=p.product_id;

CREATE VIEW public.v_sales_summary
WITH (security_invoker = true) AS
SELECT s.sale_id,s.invoice_number,s.sale_date,
       COALESCE(c.full_name,'Walk-in Customer') AS customer_name,
       COALESCE(u.full_name,'') AS cashier,
       s.service_type,s.service_description,s.subtotal,s.discount,
       s.total_amount,s.payment_method,s.reference_number,
       s.amount_paid,s.change_amount,s.status
FROM public.sales s
LEFT JOIN public.customers c ON c.customer_id=s.customer_id
LEFT JOIN public.users u ON u.user_id=s.sold_by;

-- Protect all tables from direct anonymous browser access for now.
-- The Vercel conversion will use a secure server-side connection.
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_permissions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.customers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.pets ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.confinements ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.suppliers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.inventory ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.inventory_movements ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sales ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sale_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.settings ENABLE ROW LEVEL SECURITY;

-- Helpful indexes
CREATE INDEX idx_pets_customer ON public.pets(customer_id);
CREATE INDEX idx_confinements_pet ON public.confinements(pet_id);
CREATE INDEX idx_confinements_customer ON public.confinements(customer_id);
CREATE INDEX idx_confinements_status ON public.confinements(status);
CREATE INDEX idx_products_category ON public.products(category_id);
CREATE INDEX idx_products_supplier ON public.products(supplier_id);
CREATE INDEX idx_movements_product ON public.inventory_movements(product_id);
CREATE INDEX idx_sales_customer ON public.sales(customer_id);
CREATE INDEX idx_sales_sold_by ON public.sales(sold_by);
CREATE INDEX idx_sales_date ON public.sales(sale_date);
CREATE INDEX idx_sale_items_sale ON public.sale_items(sale_id);
CREATE INDEX idx_sale_items_product ON public.sale_items(product_id);
